### ISSUE TITLE
perceptual loss

### ISSUE THREAD

**Issue by gombumsoo** [MarekPokropinski/BeautyGAN-tensorflow#1]
I'm sorry I'm not good at english.
I read your repository with interest.

I wonder how you implement the 'perceptual loss'.
I can't find a file that name image_loss which 'perceptual loss' is belonged.
Could you give me a answer?

Thanks for reading.

**Comment by MarekPokropinski** [comment]
Hi, sorry for late response, I didn't see it before. It seems like I have forgotten to upload this file. I have added it now. Details as to how perceptual loss is implemented can be found in this paper: https://arxiv.org/pdf/1603.08155.pdf.
